Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/bionic64"
	web01.vm.network "private_network", ip: "192.168.25.47"
	web01.vm.provider "virtualbox" do |vb|
	vb.memory = "1600"
	 vb.cpus = 2
  end

  config.vm.define "db01" do |db01|
    db01.vm.box = "centos/7"
	db01.vm.network "private_network", ip: "192.168.25.45"
	db01.vm.provider "virtualbox" do |vb|
	vb.memory = "1600"
	 vb.cpus = 2
  end
  
  config.vm.provision "shell", inline: <<-SHELL
     yum install mariadb-server -y
	 systemctl start mariadb
	 systemctl enable mariadb
	
	sudo mkdir -p /srv/www
    sudo chown www-data: /srv/www
    curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www
	
	cp /vagrant/wordpressconf /etc/apache2/sites-available/wordpress.conf
	sudo a2ensite wordpress
	sudo a2enmod rewrite
	sudo a2dissite 000-default
	sudo service apache2 reload
	
	mysql -u root -e 'CREATE DATABASE wordpress;'
	mysql -u root -e 'CREATE USER wordpress@localhost IDENTIFIED BY "admin123";'
	mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;'
	mysql -u root -e 'FLUSH PRIVILEGES;'
	
	sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php
	
end
